### ISSUE TITLE
Deps and CLI

### ISSUE THREAD

**Issue by viebel** [clj-commons/pomegranate#106]
Would you be interested by a PR that provides two functions that allow dependency update in compatibility with deps.edn and Clojure CLI?

I was thinking of two functions:
1. `refresh-deps` add dependencies in your global or local `deps.edn` and call `(refresh-deps)`
2. `add-deps` add one or more dependencies on the fly following `deps.edn` format e.g. `(add-deps '{tupelo {:mvn/version "0.9.103"}})`

**Comment by matthewdowney** [comment]
Bump. I think a lot of us would be interested in this!

**Comment by lread** [comment]
Hello folks, this issue is pretty old, is it still relevant/wanted?
Is it similar to the [tools.deps add-lib branch work](https://github.com/seancorfield/dot-clojure/blob/482aefe906dcc0398c1414a5fc372bb48ecac4e2/deps.edn#L102-L128) that @seancorfield uses?

**Comment by seancorfield** [comment]
Pomegranate already has `add-dependencies` although it's a bit awkward to use since you have to supply the mvn repo information. I would consider this very low priority.

**Comment by lread** [comment]
Thanks @seancorfield, much appreciated. 
I'm going to go ahead and close this one as stale for now.
Anybody who has a strong interest, please feel free to re-open.
