### ISSUE TITLE
Deps are quite stale

### ISSUE THREAD

**Issue by lread** [clj-commons/pomegranate#134]
Hiya, I was looking at pomegranate as one way to resolve deps for cljdoc api analysis when I noticed the pomegranate deps are stale.

I ran [nvd-clojure](https://github.com/rm-hull/nvd-clojure) on this repo and it reported several CVEs.

Soo... If current maintainers are good with this, I offer to:
1. Update stale deps
2. Add an automated nvd-scanner GitHub action like @slipset did for clj-yaml

**Comment by slipset** [comment]
Please the nvd scanner as a first step, and then let's address the deps in a separate PR?

**Comment by lread** [comment]
Yep, can do.

**Comment by lread** [comment]
Where to find release notes for maven libs:
* maven core [maven releases history](https://maven.apache.org/docs/history.html)
* maven resolver [mailing list announcements](https://www.mail-archive.com/search?a=1&l=users%40maven.apache.org&haswords=&x=0&y=0&from=&subject=%5E%5BANN%5D+Maven+Resolver&datewithin=1d&date=&notwords=&o=newest) 
* maven wagon - [mailing announcements](https://www.mail-archive.com/search?a=1&l=users%40maven.apache.org&haswords=&x=0&y=0&from=&subject=%5BANN%5D+Apache+Maven+Wagon&datewithin=1d&date=&notwords=&o=newest)


We are affected by https://issues.apache.org/jira/browse/MRESOLVER-241, `aether.checksums.omitChecksumsForExtensions` option replaces `aether.checksums.forSignature`. I will address this.

Looking at https://issues.apache.org/jira/browse/MRESOLVER-278 which was listed as breaking.
Will try to understand if we need to take any action here.

**Comment by lread** [comment]
@slipset would you be so kind to give this one a review and lemme know if you see any glaring issues? Note: After we merge this PR, I still want to make a few more changes, and I'll do some sanity testing with libs that use pomegranate.
