### ISSUE TITLE
Project using Pomegranate - ndevreeze/genie

### ISSUE THREAD

**Issue by ndevreeze** [clj-commons/pomegranate#167]
Hi, just wanted to let you know I have a project using Pomegranate:
https://github.com/ndevreeze/genie
It's another way of mitigating the slow startup of Clojure on the JVM, by starting a daemon in the background. Using nRepl, Pomegranate, and Babashka. 
Quoting: "Are you using Pomegranate? Let us know and we’ll add your project here!". Not sure if this is the preferred way, excuses if it's not. I could also create a PR on README.adoc. Please let me know if you have any questions.

**Comment by lread** [comment]
Cool! I'll add it in!

**Comment by ndevreeze** [comment]
Great, thanks!
