### ISSUE TITLE
User Guide correction for "deploy" example

### ISSUE THREAD

**Issue by florin-va-oltean** [clj-commons/pomegranate#168]
In User Guide, currently there is this example (at the bottom of the page):
```clojure
(aether/deploy :coordinates '[lread/mucking-around "1.2.3"]
               :jar-file (io/file "target" "some-library.jar")
               :pom-file (io/file "pom.xml")
               :repository {:url "https://repo.clojars.org"
                            :username (System/getEnv "CLOJARS_USERNAME")
                            :password (System/getEnv "CLOJARS_PASSWORD")})
```
BUT,
It should be:
```clojure
(aether/deploy :coordinates '[lread/mucking-around "1.2.3"]
               :jar-file (io/file "target" "some-library.jar")
               :pom-file (io/file "pom.xml")
               :repository {:my-repo {:url "https://repo.clojars.org"
                                                     :username (System/getenv "CLOJARS_USERNAME")
                                                     :password (System/getenv "CLOJARS_PASSWORD")}})
```

**Two differences**:
- repository map should be a map of repo-id -> repo-settings, like `{:repo-id {:url "..." :username "..." :password "..."}}`
- `System/getEnv` should be `System/getenv`

Ultimately, the first difference probably should be corrected in the code in function `deploy-artefacts` when building the object `DeployRequest` .

Note: I tested this with a private repo hosted at https://www.deps.co/

**Comment by lread** [comment]
@florin-va-oltean thanks so much for raising an issue!
I'll take a peek sometime soon.
