### ISSUE TITLE
allow managed dependencies to manage all settings

### ISSUE THREAD

**Issue by loomis** [clj-commons/pomegranate#76]
The recent addition of managed dependencies to 0.3.1 was a great enhancement.  We'd like to move to using the baked in managed dependencies, but we also need to have all of the non-coordinate settings managed, not just the versions.

Would this be of general enough interest to be considered for a PR? I have an initial implementation of it in https://github.com/SixSq/pomegranate/tree/manage-all-dep-options if people want to take a look.

**Comment by loomis** [comment]
@senior @cprice404 I've created a PR request that extends the managed dependency feature to allow all dependency options to be managed, rather than just the version. I've tested that this works with `boot`, but we're probably the only ones using that feature at the moment.  As you two created/tested the original managed dependency feature and use (I think) leiningen with managed dependencies, I was wondering if you'd be willing to review and ideally test this patch? I think that this would give Chas the confidence to merge the PR, presuming that everything looks OK.

**Comment by cprice404** [comment]
@loomis sure, I will try to take a look at it as soon as I can find some time!

**Comment by loomis** [comment]
@cprice404 Thanks.  Much appreciated.

**Comment by lread** [comment]
There has been no movement on this issue for several years, I'll go ahead and close it as stale.
Please feel free to re-open if you have an interest.
